const soldGroceriesData = [
  {
    username: 'JohnDoe',
    userEmail: 'john@example.com',
    address: '123 Main St, Cityville',
    recipeName: 'Spaghetti Bolognese',
    recipeExists: true,
    groceryItems: [
      { name: 'Tomatoes', quantity: '500g' },
      { name: 'Ground Beef', quantity: '1kg' },
      { name: 'Onions', quantity: '250g' },
      { name: 'Spaghetti', quantity: '1 lb' },
      { name: 'Canned Crushed Tomatoes', quantity: '28 oz' },
      { name: 'Tomato Paste', quantity: '6 oz' },
      { name: 'Garlic', quantity: '3 cloves' },
      { name: 'Red Wine', quantity: '1/2 cup' },
      { name: 'Olive Oil', quantity: '2 tbsp' },
      { name: 'Dried Basil', quantity: '1 tsp' },
      { name: 'Salt', quantity: '1 tsp' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    totalPrice: '₹799.70',
    purchaseDate: '2023-01-15',
    status: 'Sold',
    groceryId: 'grocery123',
    recipeId: 'recipe456',
  },
  {
    username: 'AliceSmith',
    userEmail: 'alice@example.com',
    address: '456 Oak St, Townsville',
    recipeName: 'Chicken Alfredo',
    recipeExists: true,
    groceryItems: [
      { name: 'Chicken Breast', quantity: '800g' },
      { name: 'Alfredo Sauce', quantity: '500ml' },
      { name: 'Fettuccine Pasta', quantity: '400g' },
      { name: 'Onion', quantity: '1' },
      { name: 'Garlic', quantity: '3 cloves' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Parmesan Cheese', quantity: '1/2 cup' },
      { name: 'Salt', quantity: '1 tsp' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    totalPrice: '₹919.18',
    purchaseDate: '2023-02-05',
    status: 'Sold',
    groceryId: 'grocery456',
    recipeId: 'recipe789',
  },
  {
    username: 'JaneDoe',
    userEmail: 'jane@example.com',
    address: '789 Pine St, Villagetown',
    recipeName: 'Vegetable Biryani',
    recipeExists: true,
    groceryItems: [
      { name: 'Basmati Rice', quantity: '2 cups' },
      { name: 'Mixed Vegetables', quantity: '1 cup' },
      { name: 'Onion', quantity: '1, thinly sliced' },
      { name: 'Tomato', quantity: '1, chopped' },
      { name: 'Ginger', quantity: '1-inch piece, grated' },
      { name: 'Garlic', quantity: '3 cloves, minced' },
      { name: 'Biryani Masala', quantity: '2 tsp' },
      { name: 'Ghee', quantity: '2 tbsp' },
      { name: 'Cashews', quantity: '1/4 cup' },
      { name: 'Fresh Mint Leaves', quantity: '1/4 cup' },
    ],
    totalPrice: '₹699.99',
    purchaseDate: '2023-03-12',
    status: 'Sold',
    groceryId: 'grocery789',
    recipeId: 'recipe101',
  },
  {
    username: 'SamWilson',
    userEmail: 'sam@example.com',
    address: '101 Pine St, Forestville',
    recipeName: 'Chickpea Curry',
    recipeExists: true,
    groceryItems: [
      { name: 'Chickpeas', quantity: '2 cans, drained and rinsed' },
      { name: 'Onion', quantity: '1, finely chopped' },
      { name: 'Tomato', quantity: '2, diced' },
      { name: 'Ginger-Garlic Paste', quantity: '1 tbsp' },
      { name: 'Cumin Powder', quantity: '1 tsp' },
      { name: 'Coriander Powder', quantity: '1 tsp' },
      { name: 'Turmeric Powder', quantity: '1/2 tsp' },
      { name: 'Red Chili Powder', quantity: '1 tsp' },
      { name: 'Coconut Milk', quantity: '1 cup' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Fresh Cilantro', quantity: '2 tbsp, chopped' },
    ],
    totalPrice: '₹549.50',
    purchaseDate: '2023-03-20',
    status: 'Sold',
    groceryId: 'grocery101',
    recipeId: 'recipe202',
  },
  // Add more entries as needed
];

export default soldGroceriesData;
